export const PHOTO_UPLOAD_REQUEST = "PHOTO_UPLOAD_REQUEST";
export const PHOTO_UPLOAD_SUCCESS = "PHOTO_UPLOAD_SUCCESS";
export const PHOTO_UPLOAD_FAIL = "PHOTO_UPLOAD_FAIL";

export const PHOTO_LIST_FAIL = "PHOTO_LIST_FAIL";
export const PHOTO_LIST_REQUEST = "PHOTO_LIST_REQUEST";
export const PHOTO_LIST_SUCCESS = "PHOTO_LIST_SUCCESS";


